In [2]:
# HOTEL BOOKING CANCELLATION DATA CLEANING PROJECT
# Intern Name: Your Name
# Objective:
# Clean and prepare hotel booking data for analysis

import pandas as pd
import numpy as np

df = pd.read_csv("hotel_bookings.csv")
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [2]:
print("Rows and Columns:", df.shape)
df.info()
df.describe()

Rows and Columns: (119390, 32)
<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 29.1 MB

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

# Missing Value Analysis

In [4]:
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

# Handle missing values

In [8]:
df['agent'] = df['agent'].fillna(0)
df['country'] = df['country'].fillna(df['country'].mode()[0])
df['children'] = df['children'].fillna(df['children'].median())
print(df.isnull().sum())

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               0
babies                                 0
meal                                   0
country                                0
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                                  0
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [9]:
print('company' in df.columns)

True

In [11]:
df.drop('company', axis=1, inplace=True, errors='ignore')

In [12]:
print('company' in df.columns)

False

# Duplicate Analysis

In [4]:
duplicates = df.duplicated().sum()

print("No. of duplicate values found:", duplicates)

No. of duplicate values found: 31994

In [13]:
# Remove duplicates
duplicates = df.duplicated().sum()
print(f"Number of duplicate records found: {duplicates}")

df = df.drop_duplicates()

Number of duplicate records found: 32020

In [14]:
print(f"Remaining duplicates: {df.duplicated().sum()}")

Remaining duplicates: 0

In [15]:
print(df.shape)
print(df.duplicated().sum())

(87370, 31)
0

In [21]:
df[['adults','children','babies']].describe()

             adults      children        babies
count  87370.000000  87370.000000  87370.000000
mean       1.875953      0.138675      0.010828
std        0.626473      0.455933      0.113613
min        0.000000      0.000000      0.000000
25%        2.000000      0.000000      0.000000
50%        2.000000      0.000000      0.000000
75%        2.000000      0.000000      0.000000
max       55.000000     10.000000     10.000000

# Remove Unrealistic Values

In [24]:
rows_before = len(df)

df = df[
    (df['adults'] >= 1) &
    (df['adults'] <= 10)
]
df = df[df['children'] <= 5]
df = df[df['babies'] <= 5]

rows_after = len(df)

print(f"Rows before outlier removal: {rows_before}")
print(f"Rows after outlier removal: {rows_after}")
print(f"Rows removed: {rows_before - rows_after}")
print(df[['adults','children','babies']].max())

Rows before outlier removal: 86970
Rows after outlier removal: 86970
Rows removed: 0
adults      10.0
children     3.0
babies       2.0
dtype: float64

# Handle Agent Missing Values

In [16]:
print("Missing values in agent:", df['agent'].isnull().sum())

df['agent'] = df['agent'].fillna(0)

print("Missing values after cleaning:", df['agent'].isnull().sum())


print("Missing values in country:", df['country'].isnull().sum())

df['country'] = df['country'].fillna(df['country'].mode()[0])

print("Missing values after cleaning:", df['country'].isnull().sum())


print("Missing values in children:", df['children'].isnull().sum())

df['children'] = df['children'].fillna(df['children'].median())

print("Missing values after cleaning:", df['children'].isnull().sum())


print(df.isnull().sum())

Missing values in agent: 0
Missing values after cleaning: 0
Missing values in country: 0
Missing values after cleaning: 0
Missing values in children: 0
Missing values after cleaning: 0
hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

# Outlier Detection

In [25]:
numerical_cols = ['lead_time', 'adr', 'adults', 'children', 'babies']

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]

    print(f"{col}: {len(outliers)} outliers found")

lead_time: 2371 outliers found
adr: 2506 outliers found
adults: 22484 outliers found
children: 8144 outliers found
babies: 909 outliers found

# Verify New Columns

In [19]:
# Total Guests
df['total_guests'] = (
    df['adults'] +
    df['children'] +
    df['babies']
)
# Total nights
df['total_nights'] = (
    df['stays_in_weekend_nights'] +
    df['stays_in_week_nights']
)
# Booking Status
df['booking_status'] = df['is_canceled'].map({
    0: 'Completed',
    1: 'Canceled'
})

print(df[['total_guests', 'total_nights', 'booking_status']].head())

   total_guests  total_nights booking_status
0           2.0             0      Completed
1           2.0             0      Completed
2           1.0             1      Completed
3           1.0             1      Completed
4           2.0             2      Completed

In [20]:
# Arrival Date Column
df['arrival_date'] = pd.to_datetime(
    df['arrival_date_day_of_month'].astype(str)
    + '-' +
    df['arrival_date_month']
    + '-' +
    df['arrival_date_year'].astype(str)
)

print(df['arrival_date'].head())

0   2015-07-01
1   2015-07-01
2   2015-07-01
3   2015-07-01
4   2015-07-01
Name: arrival_date, dtype: datetime64[us]

In [27]:
df.to_csv("cleaned_hotel_bookings.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

# Cancellation Rate

In [29]:
cancel_rate = df['is_canceled'].mean() * 100

print(f"Cancellation Rate: {cancel_rate:.2f}%")

Cancellation Rate: 27.50%

# Hotel Type Distribution

In [30]:
print(df['hotel'].value_counts())

hotel
City Hotel      53051
Resort Hotel    33919
Name: count, dtype: int64

# Top 10 Countries

In [31]:
print(df['country'].value_counts().head(10))

country
PRT    27722
GBR    10407
FRA     8798
ESP     7230
DEU     5372
ITA     3052
IRL     3011
BEL     2065
BRA     1983
NLD     1901
Name: count, dtype: int64

# Monthly Bookings

In [32]:
print(df['arrival_date_month'].value_counts())

arrival_date_month
August       11210
July         10008
May           8328
April         7876
June          7745
March         7470
October       6898
September     6662
February      6058
December      5086
November      4965
January       4664
Name: count, dtype: int64

# Conclusion

- Removed duplicate records from the dataset.
- Handled missing values in company, agent, country, and children columns.
- Created new features: total_guests, total_nights, booking_status, and arrival_date.
- Generated a clean dataset ready for analysis and visualization.